import 'package:flutter/material.dart';

class AppLocalizations {
  const AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = [Locale('en'), Locale('ar')];

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) {
    final instance = Localizations.of<AppLocalizations>(
      context,
      AppLocalizations,
    );
    assert(instance != null, 'AppLocalizations not found in context');
    return instance!;
  }

  String tr(String key) {
    final values =
        _localizedValues[locale.languageCode] ?? _localizedValues['en']!;
    return values[key] ?? key;
  }

  bool get isRtl => locale.languageCode == 'ar';

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'Euro Mall Loyalty',
      'get_started': 'Get started',
      'phone_login_title': 'Welcome back',
      'phone_hint': 'Phone number',
      'continue': 'Continue',
      'otp_title': 'Enter verification code',
      'resend_code': 'Resend code',
      'change_number': 'Change number',
      'dashboard': 'Dashboard',
      'points_balance': 'Points balance',
      'tier_level': 'Tier level',
      'progress_next_tier': 'Progress to next tier',
      'recent_transactions': 'Recent transactions',
      'view_all': 'View all',
      'earned': 'Earned',
      'redeemed': 'Redeemed',
      'points_history': 'Points history',
      'vouchers': 'Vouchers',
      'offers': 'Offers',
      'branches': 'Branches',
      'profile': 'Profile',
      'settings': 'Settings',
      'settings_my_profile': 'My profile',
      'settings_terms': 'Terms & conditions',
      'settings_privacy': 'Privacy policy',
      'settings_order_history': 'Order history',
      'settings_points_schema': 'Points program',
      'settings_notifications': 'Manage notifications',
      'settings_about': 'About us',
      'settings_contact': 'Contact us',
      'settings_faqs': 'FAQs',
      'sign_in_required': 'Sign in to use this feature.',
      'retry': 'Retry',
      'load_error': 'Could not load content.',
      'contact_message': 'Message',
      'your_phone': 'Your phone',
      'send_message': 'Send message',
      'message_sent': 'Thank you. We will get back to you soon.',
      'guest_welcome': 'Guest',
      'app_version_label': 'Version',
      'call_support': 'Call',
      'open_link': 'Open',
      'no_content': 'No content available.',
      'no_faqs': 'No FAQs available.',
      'orders_empty': 'No orders yet.',
      'sign_in_cta': 'Sign in',
      'phone_required': 'Enter a valid mobile number',
      'invalid_otp': 'Invalid verification code',
      'otp_incomplete': 'Enter the full code',
      'otp_resent': 'Code request sent',
      'otp_code_hint': 'Enter the verification code you received.',
      'field_required': 'This field is required',
      'invalid_email': 'Enter a valid email',
      'notif_marketing_hint': 'Marketing offers and mall updates',
      'notif_orders_hint': 'Order status and points activity',
      'notif_email_hint': 'Periodic summary by email',
      'notif_orders_title': 'Orders & points',
      'voucher_details': 'Voucher details',
      'expires': 'Expires',
      'redeem_now': 'Redeem now',
      'qr_for_redeem': 'Show this code at POS',
      'active': 'Active',
      'expired': 'Expired',
      'soon_expiring': 'Expiring soon',
      'off': 'off',
      'map_view': 'Locations',
      'tap_to_open_maps': 'Tap to open in Maps',
      'directions': 'Directions',
      'redeem_success': 'Voucher redeemed successfully',
      'maps_open_failed': 'Could not open Maps',
      'contact': 'Contact',
      'working_hours': 'Working hours',
      'language': 'Language',
      'edit_profile': 'Edit profile',
      'full_name': 'Full name',
      'gender': 'Gender',
      'dob': 'Date of birth',
      'email': 'Email',
      'save_changes': 'Save changes',
      'logout': 'Log out',
      'arabic': 'Arabic',
      'english': 'English',
      'offers_headline': 'Latest offers for you',
      'campaigns': 'Campaigns',
      'points_today': 'Points today',
      'tier_silver': 'Silver',
      'tier_gold': 'Gold',
      'tier_platinum': 'Platinum',
      'notifications': 'Notifications',
      'voucher_value': 'Voucher value',
      'minimum_spend': 'Minimum spend',
      'terms': 'Terms',
      'no_history': 'No history yet',
      'no_offers': 'No offers right now',
      'verify': 'Verify',
      'otp_sent_to': 'Code sent to',
      'male': 'Male',
      'female': 'Female',
      'other': 'Other',
      'open': 'Open',
      'closed': 'Closed',
      'explore': 'Explore',
      'notify_me': 'Notify me',
      'to': 'to',
      'login_subtitle':
          'Login with your phone number to see your points and vouchers.',
      'splash_loading': 'Loading your experience...',
      'tap_to_continue': 'Tap anywhere to continue',
      'onboard_title_1': 'Earn every visit',
      'onboard_body_1':
          'Collect points on shopping, dining, and entertainment.',
      'onboard_title_2': 'Redeem instantly',
      'onboard_body_2': 'Use vouchers and QR codes at POS with one tap.',
      'onboard_title_3': 'Find branches easily',
      'onboard_body_3': 'Discover outlets, hours, and contact info on the map.',
      'next': 'Next',
      'skip': 'Skip',
      'choose_language': 'Choose language',
      'language_subtitle':
          'You can change this anytime in your profile settings.',
      'language_settings_hint':
          'The app matches your phone language on first launch. Change it here anytime.',
      'start_now': 'Start now',
      'complete_profile': 'Complete your profile',
      'register': 'Register',
      'phone_verified': 'Phone verified',
      'lets_personalize': "Let's personalize your account",
      'submit': 'Submit',
      'welcome': 'Welcome',
      'country_code': 'Country code',
      'mobile_number': 'Mobile number',
      'personal_details': 'Personal details',
      'app_preferences': 'Preferences',
      'browse_as_guest': 'Continue without signing in',
      'sign_in': 'Sign in',
      'otp_subtitle': 'We sent a 4-digit code to your phone.',
    },
    'ar': {
      'app_title': 'برنامج ولاء يورو مول',
      'get_started': 'ابدأ الآن',
      'phone_login_title': 'أهلاً بك',
      'phone_hint': 'رقم الهاتف',
      'continue': 'استمرار',
      'otp_title': 'أدخل رمز التحقق',
      'resend_code': 'إعادة إرسال الرمز',
      'change_number': 'تغيير الرقم',
      'dashboard': 'الرئيسية',
      'points_balance': 'رصيد النقاط',
      'tier_level': 'المستوى',
      'progress_next_tier': 'التقدم نحو المستوى التالي',
      'recent_transactions': 'أحدث العمليات',
      'view_all': 'عرض الكل',
      'earned': 'مكتسبة',
      'redeemed': 'مستبدلة',
      'points_history': 'سجل النقاط',
      'vouchers': 'القسائم',
      'offers': 'العروض',
      'branches': 'الفروع',
      'profile': 'الملف الشخصي',
      'settings': 'الإعدادات',
      'settings_my_profile': 'ملفي',
      'settings_terms': 'الشروط والأحكام',
      'settings_privacy': 'سياسة الخصوصية',
      'settings_order_history': 'سجل الطلبات',
      'settings_points_schema': 'برنامج النقاط',
      'settings_notifications': 'إدارة الإشعارات',
      'settings_about': 'من نحن',
      'settings_contact': 'تواصل معنا',
      'settings_faqs': 'الأسئلة الشائعة',
      'sign_in_required': 'سجّل الدخول لاستخدام هذه الميزة.',
      'retry': 'إعادة المحاولة',
      'load_error': 'تعذر تحميل المحتوى.',
      'contact_message': 'الرسالة',
      'your_phone': 'هاتفك',
      'send_message': 'إرسال الرسالة',
      'message_sent': 'شكراً لك. سنعود إليك قريباً.',
      'guest_welcome': 'زائر',
      'app_version_label': 'الإصدار',
      'call_support': 'اتصال',
      'open_link': 'فتح',
      'no_content': 'لا يوجد محتوى.',
      'no_faqs': 'لا توجد أسئلة شائعة.',
      'orders_empty': 'لا توجد طلبات بعد.',
      'sign_in_cta': 'تسجيل الدخول',
      'phone_required': 'أدخل رقم جوال صالح',
      'invalid_otp': 'رمز التحقق غير صحيح',
      'otp_incomplete': 'أدخل الرمز كاملاً',
      'otp_resent': 'تم طلب إعادة إرسال الرمز',
      'otp_code_hint': 'أدخل رمز التحقق الذي استلمته.',
      'field_required': 'هذا الحقل مطلوب',
      'invalid_email': 'أدخل بريداً صالحاً',
      'notif_marketing_hint': 'العروض التسويقية وتحديثات المول',
      'notif_orders_hint': 'حالة الطلبات ونشاط النقاط',
      'notif_email_hint': 'ملخص دوري عبر البريد',
      'notif_orders_title': 'الطلبات والنقاط',
      'voucher_details': 'تفاصيل القسيمة',
      'expires': 'تنتهي في',
      'redeem_now': 'استبدل الآن',
      'qr_for_redeem': 'اعرض هذا الرمز عند الكاشير',
      'active': 'سارية',
      'expired': 'منتهية',
      'soon_expiring': 'تنتهي قريباً',
      'off': 'خصم',
      'map_view': 'المواقع',
      'tap_to_open_maps': 'اضغط لفتح الخريطة',
      'directions': 'الاتجاهات',
      'redeem_success': 'تم استبدال القسيمة بنجاح',
      'maps_open_failed': 'تعذر فتح الخرائط',
      'contact': 'اتصال',
      'working_hours': 'ساعات العمل',
      'language': 'اللغة',
      'edit_profile': 'تعديل البيانات',
      'full_name': 'الاسم الكامل',
      'gender': 'الجنس',
      'dob': 'تاريخ الميلاد',
      'email': 'البريد الإلكتروني',
      'save_changes': 'حفظ التغييرات',
      'logout': 'تسجيل الخروج',
      'arabic': 'العربية',
      'english': 'الإنجليزية',
      'offers_headline': 'أحدث العروض لك',
      'campaigns': 'الحملات',
      'points_today': 'نقاط اليوم',
      'tier_silver': 'فضي',
      'tier_gold': 'ذهبي',
      'tier_platinum': 'بلاتيني',
      'notifications': 'الإشعارات',
      'voucher_value': 'قيمة القسيمة',
      'minimum_spend': 'الحد الأدنى',
      'terms': 'الشروط',
      'no_history': 'لا يوجد سجل بعد',
      'no_offers': 'لا توجد عروض حالياً',
      'verify': 'تأكيد',
      'otp_sent_to': 'تم إرسال الرمز إلى',
      'male': 'ذكر',
      'female': 'أنثى',
      'other': 'آخر',
      'open': 'مفتوح',
      'closed': 'مغلق',
      'explore': 'استكشف',
      'notify_me': 'أبلغني',
      'to': 'إلى',
      'login_subtitle': 'سجّل برقم هاتفك لرؤية نقاطك وقسائمك.',
      'splash_loading': 'جاري التحميل...',
      'tap_to_continue': 'اضغط في أي مكان للمتابعة',
      'onboard_title_1': 'اكسب في كل زيارة',
      'onboard_body_1': 'اجمع النقاط على التسوق والمطاعم والترفيه.',
      'onboard_title_2': 'استبدال فوري',
      'onboard_body_2': 'استخدم القسائم ورموز QR عند الكاشير بلمسة واحدة.',
      'onboard_title_3': 'ابحث عن الفروع بسهولة',
      'onboard_body_3':
          'اكتشف الفروع وساعات العمل ومعلومات الاتصال على الخريطة.',
      'next': 'التالي',
      'skip': 'تخطي',
      'choose_language': 'اختر اللغة',
      'language_subtitle': 'يمكنك تغيير اللغة لاحقاً من إعدادات الملف الشخصي.',
      'language_settings_hint':
          'يتبع التطبيق لغة الجهاز عند أول تشغيل. يمكنك تغييرها من هنا في أي وقت.',
      'start_now': 'ابدأ الآن',
      'complete_profile': 'أكمل بياناتك',
      'register': 'تسجيل',
      'phone_verified': 'تم التحقق من الرقم',
      'lets_personalize': 'لنخصص حسابك',
      'submit': 'إرسال',
      'welcome': 'مرحباً',
      'country_code': 'رمز الدولة',
      'mobile_number': 'رقم الجوال',
      'personal_details': 'البيانات الشخصية',
      'app_preferences': 'التفضيلات',
      'browse_as_guest': 'المتابعة بدون تسجيل',
      'sign_in': 'تسجيل الدخول',
      'otp_subtitle': 'أرسلنا رمزاً مكوّناً من 4 أرقام إلى هاتفك.',
    },
  };
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) =>
      false;
}
